# Generated by Django 5.2.13 on 2026-04-30 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0021_project_updated_at_project_updated_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectobjectivecondition",
            name="note",
            field=models.TextField(blank=True, default="", max_length=400),
        ),
    ]
