"""
Django settings for dashboard project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file (simple loader, no extra dependencies)
env_file = BASE_DIR / ".env.local"
if env_file.exists():
    with open(env_file) as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, value = line.split("=", 1)
                os.environ.setdefault(key, value)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-&e&n(qvp!ktv&fjr(j8llvz4(5r0!2h9j0lpr=*40bw6z30exn"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {
            "format": "{levelname} ({name}) - {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "DEBUG",
    },
    "loggers": {
        "django": {
            "level": "DEBUG",
            "propagate": True,
        },
        "django.db.backends": {
            "level": "INFO",  # Change to DEBUG to report SQL queries (development only).
            "propagate": True,
        },
        "django.utils.autoreload": {
            "level": "INFO",  # Change to DEBUG to report file reloads (development only).
            "propagate": True,
        },
    },
}

# OIDC Settings - Loaded from .env file
OIDC_RP_CLIENT_ID = os.environ.get("DJANGO_OIDC_CLIENT_ID")
OIDC_RP_CLIENT_SECRET = os.environ.get("DJANGO_OIDC_CLIENT_SECRET")
OIDC_OP_AUTHORIZATION_ENDPOINT = os.environ.get("DJANGO_OIDC_AUTHORIZE_URL")
OIDC_OP_TOKEN_ENDPOINT = os.environ.get("DJANGO_OIDC_ACCESS_TOKEN_URL")
OIDC_OP_USER_ENDPOINT = os.environ.get("DJANGO_OIDC_USER_URL")
OIDC_OP_JWKS_ENDPOINT = os.environ.get("DJANGO_OIDC_JWKS_URL")

# The callback path will be /oidc/callback - see dashboard/dashboard/urls.py

# Optional OIDC Settings
OIDC_RP_SCOPES = os.environ.get("DJANGO_OIDC_SCOPES", "openid email profile")
OIDC_LOGIN_BUTTON_TEXT = os.environ.get(
    "DJANGO_OIDC_LOGIN_BUTTON_TEXT", "Your company login"
)
OIDC_RP_SIGN_ALGO = "RS256"
OIDC_TOKEN_USE_BASIC_AUTH = (
    True  # Use client_secret_basic instead of client_secret_post
)

# Session settings for OIDC
OIDC_RENEW_ID_TOKEN_EXPIRY_SECONDS = 15 * 60  # 15 minutes


# Application definition

INSTALLED_APPS = [
    "whitenoise.runserver_nostatic",
    "django_browser_reload",
    "tinymce",
    "projects",
    "framework",
    "dashboard",
    "django.contrib.admin",
    "django.contrib.admindocs",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

# Add OIDC app only if configured
if OIDC_RP_CLIENT_ID:
    INSTALLED_APPS.insert(3, "mozilla_django_oidc")

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.contrib.admindocs.middleware.XViewMiddleware",
    "django_browser_reload.middleware.BrowserReloadMiddleware",
]

# Add OIDC middleware only if configured
if OIDC_RP_CLIENT_ID:
    MIDDLEWARE.insert(6, "mozilla_django_oidc.middleware.SessionRefresh")

ROOT_URLCONF = "dashboard.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "dashboard.auth_decorators.oidc_settings",
            ],
        },
    },
]

WSGI_APPLICATION = "dashboard.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-gb"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
LOGIN_URL = "login"

LOGIN_REDIRECT_URL = "projects:project_list"
LOGOUT_REDIRECT_URL = "projects:project_list"

# Authentication backends
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]

# Add OIDC authentication backend only if configured
if OIDC_RP_CLIENT_ID:
    AUTHENTICATION_BACKENDS.insert(
        0, "mozilla_django_oidc.auth.OIDCAuthenticationBackend"
    )


TINYMCE_DEFAULT_CONFIG = {
    "theme": "silver",
    "width": 600,
    "height": 75,
    "menubar": False,
    "plugins": "autolink,lists,link",
    "toolbar": False,
    "statusbar": False,
    "valid_elements": "a[href|target=_blank],strong,em,p,ul,li,br",
    "content_style": "body { font-size: 13px; margin: 4px; }",
}
